# Generated by Django 3.0.5 on 2020-04-08 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200408_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.GitHubProfile'),
        ),
    ]
